### ISSUE TITLE
I have installed core and bank, and restarted the server. When I enter /bank, the server tells me that this is an unknown command

### ISSUE THREAD

**Issue by GouLiGuoJiaNaive** [Dablakbandit/Bank#4]

**Comment by Dablakbandit** [comment]
Can you provide server logs?

**Comment by GouLiGuoJiaNaive** [comment]
[18:40:39] [Server thread/INFO]: [Bank] Loading Bank v2.9.0
[18:40:39] [Server thread/INFO]: [Core] Checking update for Bank v2.9.0
[18:40:40] [Server thread/INFO]: [0;37;22m[[0;32;1mBank[0;37;22m] [0;37;1mUnknown save type in config, switching to SQLLITE[m
[18:41:41] [Server thread/INFO]: [Bank] Enabling Bank v2.9.0
[18:41:42] [Server thread/INFO]: [0;37;22m[[0;32;1mBank[0;37;22m] [0;37;1mUsing savetype SQLLITE[m
[18:41:42] [Server thread/INFO]: [0;37;22m[[0;32;1mBank[0;37;22m] [0;37;1mCleaned up 0 banks[m
[18:41:42] [Server thread/INFO]: [0;37;22m[[0;32;1mBank[0;37;22m] [0;37;1mExpire Enabled[m
[18:41:42] [Server thread/INFO]: [0;37;22m[[0;32;1mBank[0;37;22m] [0;37;1mExpireManager: Removed 0 banks[m
[18:41:42] [Server thread/INFO]: [0;37;22m[[0;32;1mBank[0;37;22m] [0;37;1mExpireManager: Checking next at 01:06:2018 00:00:00[m
[18:51:47] [Server thread/INFO]: [Bank] Disabling Bank v2.9.0
[18:51:47] [Server thread/ERROR]: Error occurred while disabling Bank v2.9.0 (Is it up to date?)
java.lang.NoClassDefFoundError: me/dablakbandit/bank/save/LoaderThread
	at me.dablakbandit.bank.BankPlugin.onDisable(BankPlugin.java:244) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:349) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:465) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:613) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.ClassNotFoundException: me.dablakbandit.bank.save.LoaderThread
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_152]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
	... 9 more

**Comment by Dablakbandit** [comment]
Fixed now, nothing to do with your error though.

Your error is cause you replaced the jar file before stopping the server, I would not recommend doing this as it causes the server to not save users banks. Stop the server then replace the jar

**Comment by GouLiGuoJiaNaive** [comment]
Running now without any errors, but the command /bank still does not work.
`[19:21:54] [Server thread/INFO]: Unknown command. Type "/help" for help.`

**Comment by Dablakbandit** [comment]
Have you updated to the latest?

**Comment by GouLiGuoJiaNaive** [comment]
I have updated to the latest build, and I deleted all the configuration files and updated the Core.

**Comment by Dablakbandit** [comment]
Can you post log file again?

**Comment by GouLiGuoJiaNaive** [comment]
[19:27:22] [Server thread/INFO]: [Bank] Loading Bank v2.9.0
[19:27:22] [Server thread/INFO]: [Core] Checking update for Bank v2.9.0
[19:27:25] [Server thread/INFO]: [Core] Enabling Core v0.0.5
[19:27:25] [Server thread/INFO]: [Core] Plugin Bank has an update! Old: v2.9.0, New: v2.9.1
[19:27:25] [Server thread/INFO]: [Core] Continuing in 3
[19:27:26] [Server thread/INFO]: [Core] Continuing in 2
[19:27:27] [Server thread/INFO]: [Core] Continuing in 1
[19:28:25] [Server thread/INFO]: [0;37;22m[[0;32;1mBank[0;37;22m] [0;37;1mUsing savetype SQLLITE[m
[19:28:25] [Server thread/INFO]: [0;37;22m[[0;32;1mBank[0;37;22m] [0;37;1mCleaned up 0 banks[m
[19:28:25] [Server thread/INFO]: [0;37;22m[[0;32;1mBank[0;37;22m] [0;37;1mExpire Enabled[m
[19:28:25] [Server thread/INFO]: [0;37;22m[[0;32;1mBank[0;37;22m] [0;37;1mExpireManager: Removed 0 banks[m
[19:28:25] [Server thread/INFO]: [0;37;22m[[0;32;1mBank[0;37;22m] [0;37;1mExpireManager: Checking next at 01:06:2018 00:00:00[m

**Comment by Dablakbandit** [comment]
Latest is 2.9.1, I posted an update with the fix
Should fix this problem :)

**Comment by GouLiGuoJiaNaive** [comment]
Great, The problem is solved.

**Comment by Dablakbandit** [comment]
Glad to help
